[package]
name = "scanner"
version = "0.1.0"
authors = ["yuchunzhou <chunzhou.yu@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
trust-dns-resolver = "0.19.5"
